/**
 * Types
 */
export const ACYNC_FETCH_RECEIPT_DATA_REQUEST = 'ACYNC_FETCH_RECEIPT_DATA_REQUEST';
export const ACYNC_FETCH_RECEIPT_DATA_SUCCESS = 'ACYNC_FETCH_RECEIPT_DATA_SUCCESS';
export const ACYNC_FETCH_RECEIPT_DATA_ERROR = 'ACYNC_FETCH_RECEIPT_DATA_ERROR';