/**
 * Types
 */
export const ACYNC_FETCH_RECEIPT_DATA_REQUEST = 'ACYNC_FETCH_RECEIPT_DATA_REQUEST';
export const ACYNC_FETCH_RECEIPT_DATA_SUCCESS = 'ACYNC_FETCH_RECEIPT_DATA_SUCCESS';
export const ACYNC_FETCH_RECEIPT_DATA_ERROR = 'ACYNC_FETCH_RECEIPT_DATA_ERROR';

export const ACYNC_FETCH_FRUITS_REQUEST = 'ACYNC_FETCH_FRUITS_REQUEST';
export const ACYNC_FETCH_FRUITS_SUCCESS = 'ACYNC_FETCH_FRUITS_SUCCESS';
export const ACYNC_FETCH_FRUITS_ERROR = 'ACYNC_FETCH_FRUITS_ERROR';